name: Compile OpenBLAS on Windows
run-name: Compile OpenBLAS on Windows - ${{ github.sha }}
on: workflow_dispatch
jobs:
  compile:
    name: Compile OpenBLAS
    runs-on: windows-latest
    steps:
      - name: Compile
        continue-on-error: true
        run: |
          ls C:\
          ls C:\Miniconda
          ls "C:\Program Files\"
          ls "C:\Program Files\Microsoft Visual Studio\"
          ls "C:\Program Files\Microsoft Visual Studio\2022\"
          ls "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\"
          ls "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\vc\"
          ls "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\vc\Auxiliary\"
          ls "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\vc\Auxiliary\Build\"
          C:\Miniconda\shell\condabin\conda-hook.ps1
          conda update -n base conda
          conda config --add channels conda-forge
          conda install -y cmake flang clangdev perl libflang ninja
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\vc\Auxiliary\Build\vcvars64.bat"
          link
          conda activate
          link
          git clone https://github.com/OpenMathLib/OpenBLAS.git
          cd OpenBLAS
          echo $env:CONDA_PREFIX
          $env:LIB = "$env:CONDA_PREFIX\Library\lib;$env:LIB"
          $env:CPATH = "$env:CONDA_PREFIX\Library\include;$env:CPATH"
          echo $env:LIB
          echo $env:CPATH
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          ls
          ls lib
